name: Docker Image PR Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Control Plane Backend
        uses: docker/build-push-action@v5
        with:
          context: ./source/go-backend
          file: ./source/go-backend/Dockerfile
          push: false

      - name: Build Dashboard
        uses: docker/build-push-action@v5
        with:
          context: ./source
          file: ./source/dashboard/Dockerfile
          push: false
